-- =============================================================================
-- ContractLens CLM - Oracle Schema (Document-Aligned Metadata + Workflow Model)
-- =============================================================================

-- Cleanup (safe drop)
BEGIN EXECUTE IMMEDIATE 'DROP VIEW contract_validation_dv'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE contract_audit_trail CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE contract_parameters_extracted CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE metadata_options CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE master_extraction_rules CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE contracts_master CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- -----------------------------------------------------------------------------
-- Core Contract Master Table (includes all metadata fields from requirement docs)
-- -----------------------------------------------------------------------------
CREATE TABLE contracts_master (
    contract_id                          VARCHAR2(50) PRIMARY KEY,
    organization                         VARCHAR2(100) NOT NULL,
    business_unit                        VARCHAR2(100) NOT NULL,
    location                             VARCHAR2(100),
    department                           VARCHAR2(100),
    customer_partner_name                VARCHAR2(200),
    financial_year                       VARCHAR2(20),
    contract_type                        VARCHAR2(100) NOT NULL,
    agreement_type                       VARCHAR2(100) NOT NULL,
    additional_info                      CLOB,

    contract_number                      VARCHAR2(120),
    version_amendment_number             VARCHAR2(120),
    execution_type                       VARCHAR2(50),
    governing_entity                     VARCHAR2(120),
    jurisdiction                         VARCHAR2(120),
    governing_law                        VARCHAR2(120),
    legal_names_of_parties               CLOB,
    registered_addresses                 CLOB,
    cin_registration_numbers             CLOB,
    authorized_signatories               CLOB,
    contact_persons                      CLOB,
    party_roles                          CLOB,
    affiliates_subsidiaries_involved     CLOB,
    effective_date                       DATE,

    uploaded_filename                    VARCHAR2(255),
    uploaded_content_type                VARCHAR2(120),
    document_text                        CLOB,

    workflow_state                       VARCHAR2(30) DEFAULT 'STAGED_DRAFT' NOT NULL,
    checked_out_by                       VARCHAR2(100),
    checkout_expiry                      TIMESTAMP WITH TIME ZONE,
    document_version                     NUMBER DEFAULT 1 NOT NULL,
    created_by                           VARCHAR2(100),
    approved_by                          VARCHAR2(100),
    created_at                           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at                           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_updated                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- -----------------------------------------------------------------------------
-- Rule Master Table (Step-2 rule maintenance from docs)
-- -----------------------------------------------------------------------------
CREATE TABLE master_extraction_rules (
    rule_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_type      VARCHAR2(100) NOT NULL,
    agreement_type     VARCHAR2(100) NOT NULL,
    parameter_head     VARCHAR2(150) NOT NULL,
    parameter_name     VARCHAR2(150) NOT NULL,
    parameter_logic    VARCHAR2(250),
    is_active          NUMBER(1) DEFAULT 1 NOT NULL,
    created_by         VARCHAR2(100),
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_master_rule_signature UNIQUE (contract_type, agreement_type, parameter_head, parameter_name)
);

-- -----------------------------------------------------------------------------
-- Metadata Option Table (dropdown source from DB)
-- -----------------------------------------------------------------------------
CREATE TABLE metadata_options (
    option_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category           VARCHAR2(80) NOT NULL,
    value              VARCHAR2(200) NOT NULL,
    is_active          NUMBER(1) DEFAULT 1 NOT NULL,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_metadata_category_value UNIQUE (category, value)
);

CREATE INDEX idx_metadata_category ON metadata_options(category);

-- -----------------------------------------------------------------------------
-- Parameter Extraction Table (original vs changed + citation + score)
-- -----------------------------------------------------------------------------
CREATE TABLE contract_parameters_extracted (
    parameter_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id        VARCHAR2(50) NOT NULL REFERENCES contracts_master(contract_id) ON DELETE CASCADE,
    header_name        VARCHAR2(150) NOT NULL,
    param_name         VARCHAR2(150) NOT NULL,
    original_extract   CLOB,
    user_override      CLOB,
    match_score        NUMBER(4,3),
    citation_text      CLOB,
    citation_start     NUMBER,
    citation_end       NUMBER,
    spatial_json       CLOB,
    vector_embed       CLOB,
    source_query       VARCHAR2(250),
    is_user_added      NUMBER(1) DEFAULT 0 NOT NULL,
    is_verified        NUMBER(1) DEFAULT 0 NOT NULL,
    verification_note  CLOB,
    last_modified      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- -----------------------------------------------------------------------------
-- Audit Trail Table (immutable transaction ledger)
-- -----------------------------------------------------------------------------
CREATE TABLE contract_audit_trail (
    audit_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id        VARCHAR2(50) NOT NULL REFERENCES contracts_master(contract_id) ON DELETE CASCADE,
    action_type        VARCHAR2(50) NOT NULL,
    field_changed      VARCHAR2(150),
    old_value_clob     CLOB,
    new_value_clob     CLOB,
    modified_by        VARCHAR2(100) NOT NULL,
    logged_timestamp   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- -----------------------------------------------------------------------------
-- Optional Oracle JSON-Relational Duality View
-- -----------------------------------------------------------------------------
CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW contract_validation_dv AS
SELECT JSON {
    'contractId'            : c.contract_id,
    'organization'          : c.organization,
    'businessUnit'          : c.business_unit,
    'location'              : c.location,
    'department'            : c.department,
    'customerPartnerName'   : c.customer_partner_name,
    'financialYear'         : c.financial_year,
    'contractType'          : c.contract_type,
    'agreementType'         : c.agreement_type,
    'additionalInfo'        : c.additional_info,
    'contractNumber'        : c.contract_number,
    'versionAmendmentNo'    : c.version_amendment_number,
    'executionType'         : c.execution_type,
    'governingEntity'       : c.governing_entity,
    'jurisdiction'          : c.jurisdiction,
    'governingLaw'          : c.governing_law,
    'legalNamesOfParties'   : c.legal_names_of_parties,
    'registeredAddresses'   : c.registered_addresses,
    'cinRegistrationNos'    : c.cin_registration_numbers,
    'authorizedSignatories' : c.authorized_signatories,
    'contactPersons'        : c.contact_persons,
    'partyRoles'            : c.party_roles,
    'affiliatesSubsidiaries': c.affiliates_subsidiaries_involved,
    'effectiveDate'         : c.effective_date,
    'status'                : c.workflow_state,
    'checkedOutBy'          : c.checked_out_by,
    'checkoutExpiry'        : c.checkout_expiry,
    'version'               : c.document_version,
    'parameters'            : [
        SELECT JSON {
            'paramId'          : p.parameter_id,
            'header'           : p.header_name,
            'name'             : p.param_name,
            'machineExtract'   : p.original_extract,
            'userOverride'     : p.user_override,
            'confidence'       : p.match_score,
            'citationText'     : p.citation_text,
            'citationStart'    : p.citation_start,
            'citationEnd'      : p.citation_end,
            'coordinates'      : p.spatial_json,
            'sourceQuery'      : p.source_query,
            'isUserAdded'      : p.is_user_added,
            'isVerified'       : p.is_verified
        }
        FROM contract_parameters_extracted p WITH INSERT UPDATE DELETE
        WHERE c.contract_id = p.contract_id
    ]
}
FROM contracts_master c WITH INSERT UPDATE DELETE;
