-- =============================================================================
-- ContractLens CLM — Oracle 23ai Schema
-- Changes from v1:
--   • contracts_master.document_blob      BLOB     — stores raw uploaded file
--   • contracts_master.document_vector    VECTOR(1024, FLOAT32) — doc embedding
--   • contract_parameters_extracted.vector_embed VECTOR(1024, FLOAT32)
--   • VECTOR indexes using IVF for fast ANN search
--   • SQLite fallback removed
-- =============================================================================

-- Cleanup (safe drop order: dependents first)
BEGIN EXECUTE IMMEDIATE 'DROP VIEW contract_validation_dv'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE contract_audit_trail CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE contract_document_chunks CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE contract_parameters_extracted CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE metadata_options CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE master_extraction_rules CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE contracts_master CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ─────────────────────────────────────────────────────────────────────────────
-- contracts_master
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE contracts_master (
    contract_id                          VARCHAR2(50) PRIMARY KEY,
    organization                         VARCHAR2(100) NOT NULL,
    business_unit                        VARCHAR2(100) NOT NULL,
    location                             VARCHAR2(100),
    department                           VARCHAR2(100),
    customer_partner_name                VARCHAR2(200),
    financial_year                       VARCHAR2(20),
    contract_type                        VARCHAR2(100) NOT NULL,
    agreement_type                       VARCHAR2(100) NOT NULL,
    additional_info                      CLOB,

    -- Basic contract metadata fields
    contract_number                      VARCHAR2(120),
    version_amendment_number             VARCHAR2(120),
    execution_type                       VARCHAR2(50),
    governing_entity                     VARCHAR2(120),
    jurisdiction                         VARCHAR2(120),
    governing_law                        VARCHAR2(120),
    legal_names_of_parties               CLOB,
    registered_addresses                 CLOB,
    cin_registration_numbers             CLOB,
    authorized_signatories               CLOB,
    contact_persons                      CLOB,
    party_roles                          CLOB,
    affiliates_subsidiaries_involved     CLOB,
    effective_date                       DATE,

    uploaded_filename                    VARCHAR2(255),
    uploaded_content_type                VARCHAR2(120),

    -- Raw file stored as BLOB (PDF/DOCX bytes) — served to frontend PDF viewer
    document_blob                        BLOB,

    -- Plain-text extracted from document (for LLM context window)
    document_text                        CLOB,

    -- 1024-dim GGUF embedding of document text
    -- Used for document-level semantic search
    document_vector                      VECTOR(1024, FLOAT32),

    workflow_state                       VARCHAR2(30) DEFAULT 'STAGED_DRAFT' NOT NULL,
    checked_out_by                       VARCHAR2(100),
    checkout_expiry                      TIMESTAMP WITH TIME ZONE,
    document_version                     NUMBER DEFAULT 1 NOT NULL,
    created_by                           VARCHAR2(100),
    approved_by                          VARCHAR2(100),
    created_at                           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at                           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_updated                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- master_extraction_rules
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE master_extraction_rules (
    rule_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_type      VARCHAR2(100) NOT NULL,
    agreement_type     VARCHAR2(100) NOT NULL,
    parameter_head     VARCHAR2(150) NOT NULL,
    parameter_name     VARCHAR2(150) NOT NULL,
    parameter_logic    VARCHAR2(250),
    is_active          NUMBER(1) DEFAULT 1 NOT NULL,
    created_by         VARCHAR2(100),
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_master_rule_signature UNIQUE (contract_type, agreement_type, parameter_head, parameter_name)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- metadata_options
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE metadata_options (
    option_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category           VARCHAR2(80) NOT NULL,
    value              VARCHAR2(200) NOT NULL,
    is_active          NUMBER(1) DEFAULT 1 NOT NULL,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_metadata_category_value UNIQUE (category, value)
);

CREATE INDEX idx_metadata_category ON metadata_options(category);

-- ─────────────────────────────────────────────────────────────────────────────
-- contract_parameters_extracted
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE contract_parameters_extracted (
    parameter_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id        VARCHAR2(50) NOT NULL
                           REFERENCES contracts_master(contract_id) ON DELETE CASCADE,
    header_name        VARCHAR2(150) NOT NULL,
    param_name         VARCHAR2(150) NOT NULL,

    -- LLM-extracted raw value
    original_extract   CLOB,
    -- Human-edited value (takes precedence in display)
    user_override      CLOB,

    match_score        NUMBER(4,3),

    -- Exact quoted sentence(s) from the document text
    citation_text      CLOB,
    -- Character offsets within document_text (for plain-text highlight)
    citation_start     NUMBER,
    citation_end       NUMBER,

    -- PDF spatial coordinates: {"page": N, "rects": [[x0,y0,x1,y1],...]}
    -- Used by the frontend PDF.js viewer to draw highlight overlays
    spatial_json       JSON,

    -- 1024-dim embedding of citation_text — for VECTOR_DISTANCE RAG search
    vector_embed       VECTOR(1024, FLOAT32),

    source_query       VARCHAR2(250),
    is_user_added      NUMBER(1) DEFAULT 0 NOT NULL,
    is_verified        NUMBER(1) DEFAULT 0 NOT NULL,
    verification_note  CLOB,
    last_modified      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- contract_audit_trail
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE contract_audit_trail (
    audit_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id        VARCHAR2(50) NOT NULL
                           REFERENCES contracts_master(contract_id) ON DELETE CASCADE,
    action_type        VARCHAR2(50) NOT NULL,
    field_changed      VARCHAR2(150),
    old_value_clob     CLOB,
    new_value_clob     CLOB,
    modified_by        VARCHAR2(100) NOT NULL,
    logged_timestamp   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- contract_document_chunks
-- Paragraph-level chunks with per-line spatial coordinates for precise
-- frontend highlighting. Populated on every document upload / re-extract.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE contract_document_chunks (
    chunk_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id  VARCHAR2(50) NOT NULL
                     REFERENCES contracts_master(contract_id) ON DELETE CASCADE,
    chunk_index  NUMBER(6) NOT NULL,
    chunk_text   CLOB NOT NULL,
    char_start   NUMBER(10) NOT NULL,
    char_end     NUMBER(10) NOT NULL,
    -- Array of per-line bounding boxes: [[page,x0,y0,x1,y1,pw,ph],...]
    spatial_json JSON,
    -- Paragraph-level embedding for granular cosine search
    chunk_vector VECTOR(1024, FLOAT32),
    CONSTRAINT uq_chunk_contract_idx UNIQUE (contract_id, chunk_index)
);


-- ─────────────────────────────────────────────────────────────────────────────
-- Vector indexes (Oracle 23ai IVF — approximate nearest-neighbour)
-- Run AFTER inserting a reasonable number of rows (IVF needs training data).
-- ─────────────────────────────────────────────────────────────────────────────

-- Index on parameter embeddings (primary RAG retrieval target)
CREATE VECTOR INDEX idx_param_vector
ON contract_parameters_extracted(vector_embed)
ORGANIZATION INMEMORY NEIGHBOR GRAPH
DISTANCE COSINE
WITH TARGET ACCURACY 95;

-- Index on document embeddings (document-level retrieval)
CREATE VECTOR INDEX idx_doc_vector
ON contracts_master(document_vector)
ORGANIZATION INMEMORY NEIGHBOR GRAPH
DISTANCE COSINE
WITH TARGET ACCURACY 95;

-- Index on paragraph-chunk embeddings (granular RAG — primary extraction source)
CREATE VECTOR INDEX idx_chunk_vector
ON contract_document_chunks(chunk_vector)
ORGANIZATION INMEMORY NEIGHBOR GRAPH
DISTANCE COSINE
WITH TARGET ACCURACY 95;


-- ─────────────────────────────────────────────────────────────────────────────
-- Oracle JSON-Relational Duality View (unchanged, for external consumers)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW contract_validation_dv AS
SELECT JSON {
    'contractId'            : c.contract_id,
    'organization'          : c.organization,
    'businessUnit'          : c.business_unit,
    'location'              : c.location,
    'department'            : c.department,
    'customerPartnerName'   : c.customer_partner_name,
    'financialYear'         : c.financial_year,
    'contractType'          : c.contract_type,
    'agreementType'         : c.agreement_type,
    'additionalInfo'        : c.additional_info,
    'contractNumber'        : c.contract_number,
    'versionAmendmentNo'    : c.version_amendment_number,
    'executionType'         : c.execution_type,
    'governingEntity'       : c.governing_entity,
    'jurisdiction'          : c.jurisdiction,
    'governingLaw'          : c.governing_law,
    'legalNamesOfParties'   : c.legal_names_of_parties,
    'registeredAddresses'   : c.registered_addresses,
    'cinRegistrationNos'    : c.cin_registration_numbers,
    'authorizedSignatories' : c.authorized_signatories,
    'contactPersons'        : c.contact_persons,
    'partyRoles'            : c.party_roles,
    'affiliatesSubsidiaries': c.affiliates_subsidiaries_involved,
    'effectiveDate'         : c.effective_date,
    'status'                : c.workflow_state,
    'checkedOutBy'          : c.checked_out_by,
    'checkoutExpiry'        : c.checkout_expiry,
    'version'               : c.document_version,
    'parameters'            : [
        SELECT JSON {
            'paramId'        : p.parameter_id,
            'header'         : p.header_name,
            'name'           : p.param_name,
            'machineExtract' : p.original_extract,
            'userOverride'   : p.user_override,
            'confidence'     : p.match_score,
            'citationText'   : p.citation_text,
            'citationStart'  : p.citation_start,
            'citationEnd'    : p.citation_end,
            'spatialCoords'  : p.spatial_json,
            'sourceQuery'    : p.source_query,
            'isUserAdded'    : p.is_user_added,
            'isVerified'     : p.is_verified
        }
        FROM contract_parameters_extracted p WITH INSERT UPDATE DELETE
        WHERE c.contract_id = p.contract_id
    ]
}
FROM contracts_master c WITH INSERT UPDATE DELETE;