from __future__ import annotations

import sys
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import inspect, text

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.config import settings
from app.database import AsyncSessionLocal, Base, engine, get_database_driver
from app.routes import assistant, contracts, dashboard, maintenance, metadata, rules, verification
from app.services.bootstrap import seed_defaults
from app.services.llm import cohere_llm
from app.services.logger import clm_logger


# ── Table classification ───────────────────────────────────────────────────────────────
#
# _CORE_TABLES: absence of any of these triggers a full drop-and-rebuild.
# _PUBLISHED_TABLES: absence of any of these triggers additive-only CREATE TABLE
#                    without dropping core tables. Published tables are a separate
#                    trust zone and must never force destruction of draft data.

_CORE_TABLES: frozenset[str] = frozenset({
    "contracts_master",
    "contract_parameters_extracted",
    "contract_document_chunks",
    "contract_audit_trail",
    "master_extraction_rules",
    "metadata_options",
    "contract_tag_suggestions",
})

_PUBLISHED_TABLES: frozenset[str] = frozenset({
    "published_contracts",
    "published_parameters",
    "published_chunks",
})

# Union of all expected tables (for backwards-compatible references).
_EXPECTED_TABLES: frozenset[str] = _CORE_TABLES | _PUBLISHED_TABLES

# VECTOR column dimension requirements. If any actual dim doesn't match the
# configured EMBEDDING_VECTOR_DIM, the whole schema is rebuilt.
_VECTOR_COLUMN_DIMS: dict[str, dict[str, int]] = {
    "contracts_master": {
        "document_vector": settings.embedding_vector_dim,
    },
    "contract_parameters_extracted": {
        "vector_embed": settings.embedding_vector_dim,
    },
    "contract_document_chunks": {
        "chunk_vector": settings.embedding_vector_dim,
    },
    "published_parameters": {
        "vector_embed": settings.embedding_vector_dim,
    },
    "published_chunks": {
        "chunk_vector": settings.embedding_vector_dim,
    },
}

# Identity columns — their absence means the schema was created without Oracle
# GENERATED BY DEFAULT AS IDENTITY (e.g., an old SQLite migration).
_IDENTITY_COLUMNS: dict[str, set[str]] = {
    "contract_parameters_extracted": {"parameter_id"},
    "contract_audit_trail": {"audit_id"},
    "master_extraction_rules": {"rule_id"},
    "metadata_options": {"option_id"},
    "contract_document_chunks": {"chunk_id"},
    "published_contracts": {"published_id"},
    "published_parameters": {"published_param_id"},
    "published_chunks": {"published_chunk_id"},
    "contract_tag_suggestions": {"suggestion_id"},
}

# Oracle VECTOR index DDL — each wrapped in anonymous PL/SQL so the block
# silently ignores ORA-00955 (object already exists) on restart.
# INMEMORY NEIGHBOR GRAPH is the Oracle 26ai HNSW index type (zero training
# data requirement, suitable for small-to-medium datasets).
_VECTOR_INDEX_DDL: list[tuple[str, str]] = [
    (
        "idx_chunk_vector",
        """
        CREATE VECTOR INDEX idx_chunk_vector
        ON contract_document_chunks(chunk_vector)
        ORGANIZATION INMEMORY NEIGHBOR GRAPH
        DISTANCE COSINE
        WITH TARGET ACCURACY 95
        """,
    ),
    (
        "idx_param_vector",
        """
        CREATE VECTOR INDEX idx_param_vector
        ON contract_parameters_extracted(vector_embed)
        ORGANIZATION INMEMORY NEIGHBOR GRAPH
        DISTANCE COSINE
        WITH TARGET ACCURACY 95
        """,
    ),
    (
        "idx_doc_vector",
        """
        CREATE VECTOR INDEX idx_doc_vector
        ON contracts_master(document_vector)
        ORGANIZATION INMEMORY NEIGHBOR GRAPH
        DISTANCE COSINE
        WITH TARGET ACCURACY 95
        """,
    ),
    (
        "idx_pub_param_vector",
        """
        CREATE VECTOR INDEX idx_pub_param_vector
        ON published_parameters(vector_embed)
        ORGANIZATION INMEMORY NEIGHBOR GRAPH
        DISTANCE COSINE
        WITH TARGET ACCURACY 95
        """,
    ),
    (
        "idx_pub_chunk_vector",
        """
        CREATE VECTOR INDEX idx_pub_chunk_vector
        ON published_chunks(chunk_vector)
        ORGANIZATION INMEMORY NEIGHBOR GRAPH
        DISTANCE COSINE
        WITH TARGET ACCURACY 95
        """,
    ),
]


# ── Synchronous schema inspection & drop logic (runs inside run_sync) ─────────

def _ensure_schema(sync_conn) -> None:
    """
    Inspects the live Oracle schema and applies one of two strategies:

    STRATEGY A — Additive migration (published tables only are missing):
      If the only missing tables are a subset of _PUBLISHED_TABLES AND
      contracts_master already exists, we call create_all with a filtered
      table list. Existing draft data is preserved entirely.

    STRATEGY B — Full rebuild (core draft table missing):
      If ANY table from _CORE_TABLES is missing, OR if a VECTOR column has
      the wrong dimension, OR if an Identity column is absent, drop all ORM
      tables and let create_all rebuild from scratch.

    For non-Oracle dialects (e.g., SQLite in dev), this function is a no-op —
    SQLAlchemy handles those natively.
    """
    if sync_conn.dialect.name != "oracle":
        return

    inspector = inspect(sync_conn)
    existing_tables: set[str] = set(inspector.get_table_names())

    # ── Classify missing tables ─────────────────────────────────────────────────
    missing_core = _CORE_TABLES - existing_tables
    missing_published = _PUBLISHED_TABLES - existing_tables

    # ── STRATEGY A: published-only tables are missing, core is intact ─────────
    if not missing_core and missing_published:
        clm_logger.info(
            f"[Schema] Core tables intact. Missing published tables only: "
            f"{sorted(missing_published)}. Applying additive migration."
        )
        # Filter ORM metadata to only the missing published tables.
        published_orm_tables = [
            Base.metadata.tables[t]
            for t in missing_published
            if t in Base.metadata.tables
        ]
        if published_orm_tables:
            Base.metadata.create_all(sync_conn, tables=published_orm_tables)
            clm_logger.info(
                f"[Schema] Additive migration complete: created {sorted(missing_published)}."
            )
        return

    # ── STRATEGY B: core table missing — trigger full rebuild ────────────────
    if missing_core:
        clm_logger.warning(
            f"[Schema] Missing CORE tables detected: {sorted(missing_core)}. "
            "Dropping all ORM tables and recreating from metadata."
        )
        Base.metadata.drop_all(sync_conn)
        return  # create_all will run immediately after in the lifespan caller

    # ── Check: VECTOR dimension mismatch ──────────────────────────────────
    for table_name, columns in _VECTOR_COLUMN_DIMS.items():
        if table_name not in existing_tables:
            continue
        col_map = {
            col["name"].lower(): col
            for col in inspector.get_columns(table_name)
        }
        for col_name, expected_dim in columns.items():
            col_info = col_map.get(col_name)
            if col_info is None:
                continue
            actual_dim = getattr(col_info.get("type"), "dim", None)
            if actual_dim is not None and actual_dim != expected_dim:
                clm_logger.warning(
                    f"[Schema] VECTOR dim mismatch on {table_name}.{col_name}: "
                    f"expected={expected_dim}, actual={actual_dim}. Rebuilding."
                )
                Base.metadata.drop_all(sync_conn)
                return

    # ── Check: missing Identity columns ────────────────────────────────────
    for table_name, identity_cols in _IDENTITY_COLUMNS.items():
        if table_name not in existing_tables:
            continue
        col_map = {
            col["name"].lower(): col
            for col in inspector.get_columns(table_name)
        }
        for col_name in identity_cols:
            col_info = col_map.get(col_name)
            if col_info is not None and col_info.get("identity") is None:
                clm_logger.warning(
                    f"[Schema] Identity missing on {table_name}.{col_name}. Rebuilding."
                )
                Base.metadata.drop_all(sync_conn)
                return

    clm_logger.info("[Schema] All tables present and schema valid — no rebuild required.")


# ── Oracle VECTOR index creation (async, idempotent via PL/SQL exception block)

async def _ensure_vector_indexes(conn) -> None:
    """
    Creates Oracle 26ai VECTOR indexes if they do not already exist.
    Each DDL statement is wrapped in an anonymous PL/SQL block that silently
    swallows ORA-00955 (name already used by an existing object), making this
    safe to call on every restart.

    Skipped entirely for non-Oracle dialects.
    """
    if engine.dialect.name != "oracle":
        return

    for index_name, ddl in _VECTOR_INDEX_DDL:
        plsql = f"""
        BEGIN
            EXECUTE IMMEDIATE q'[{ddl.strip()}]';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE = -955 THEN NULL;  -- ORA-00955: name already used
                ELSE RAISE;
                END IF;
        END;
        """
        try:
            await conn.execute(text(plsql))
            clm_logger.info(f"[Schema] VECTOR index '{index_name}' ensured.")
        except Exception as exc:
            # Non-fatal: VECTOR indexes improve performance but queries fall back
            # to full table scans without them. Log and continue.
            clm_logger.warning(
                f"[Schema] Could not create VECTOR index '{index_name}': {exc}. "
                "Queries will use full scans. This is expected on non-26ai Oracle instances."
            )


# ── FastAPI lifespan ───────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(_: FastAPI):
    """
    Startup sequence (runs once per server process start):

      1. _ensure_schema   — drop stale/partial schema if needed (sync, inside run_sync).
      2. create_all       — create any missing ORM-mapped tables (idempotent).
      3. _ensure_vector_indexes — create VECTOR ANN indexes (idempotent PL/SQL).
      4. seed_defaults    — insert seed rules and metadata options (upsert-safe).

    Shutdown:
      5. Close the LLM HTTP client pool.
    """
    clm_logger.info("[Startup] Beginning schema bootstrap...")

    try:
        async with engine.begin() as conn:
            # Step 1 + 2: inspect, optionally drop, then create all ORM tables.
            await conn.run_sync(_ensure_schema)
            await conn.run_sync(Base.metadata.create_all)
            clm_logger.info("[Startup] ORM tables created/verified.")

            # Step 3: VECTOR indexes (Oracle 26ai only, idempotent).
            await _ensure_vector_indexes(conn)

        # Step 4: Seed default rules and metadata (runs in its own session).
        async with AsyncSessionLocal() as session:
            await seed_defaults(session)
            clm_logger.info("[Startup] Seed data applied.")

        clm_logger.info("[Startup] Schema bootstrap complete. Server ready.")

        yield

    finally:
        await cohere_llm.aclose()
        clm_logger.info("[Shutdown] LLM client closed.")


# ── FastAPI app ────────────────────────────────────────────────────────────────

app = FastAPI(
    title=settings.app_name,
    description=(
        "Contract lifecycle ingestion, rule-based extraction, verification, "
        "approval, and dashboard APIs."
    ),
    version=settings.app_version,
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(contracts.router, prefix=settings.api_prefix)
app.include_router(dashboard.router, prefix=settings.api_prefix)
app.include_router(assistant.router, prefix=settings.api_prefix)
app.include_router(rules.router, prefix=settings.api_prefix)
app.include_router(metadata.router, prefix=settings.api_prefix)
app.include_router(verification.router, prefix=settings.api_prefix)
app.include_router(maintenance.router, prefix=settings.api_prefix)


@app.get(f"{settings.api_prefix}/health", tags=["System Diagnostics"])
async def health_diagnostics():
    return {
        "status": "operational",
        "environment": settings.app_env,
        "database_driver": get_database_driver(),
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)